### ISSUE TITLE
DayZPosConv Export Format DayZ Editor Scene

### ISSUE THREAD

**Issue by DreierPaschCommunity** [virtyvoid/DayZPosConv#1]
Hello, I tried your useful tool, unfortunately the DayZ Editor cannot read the exported "DayZ Editor Scene" format. The problem is with the formatting of the export file. This is created in the UTF-8-BOM format but must be UTF-8. With UTF-8 it works :-)

**Comment by virtyvoid** [comment]
Good find. Fixed, thanks!
